/**
 * CSP Nonce Middleware
 *
 * Generates a cryptographically random nonce per request for use in
 * Content-Security-Policy directives. The nonce is stored in
 * `res.locals.cspNonce` and can be:
 *
 *   1. Referenced in Helmet CSP via the `cspNonceDirective()` helper function
 *   2. Injected into HTML responses as `<script nonce="...">` attributes
 *
 * Nonces are 128-bit (16 bytes) base64-encoded values — sufficient entropy
 * to prevent brute-force attacks within a single request lifetime.
 *
 * ## Usage
 *
 * ```typescript
 * // Register middleware BEFORE Helmet:
 * app.use(cspNonceMiddleware);
 * app.use(helmet({
 *   contentSecurityPolicy: {
 *     directives: {
 *       scriptSrc: ["'self'", cspNonceDirective()],
 *     }
 *   }
 * }));
 *
 * // In HTML template / SPA fallback:
 * const nonce = res.locals.cspNonce;
 * html = html.replace('<script', `<script nonce="${nonce}"`);
 * ```
 *
 * @module
 */
import crypto from 'crypto';
import type { Request, Response, NextFunction } from 'express';
import type { IncomingMessage, ServerResponse } from 'http';

/**
 * Express middleware that generates a per-request CSP nonce.
 *
 * Must be registered before Helmet so the nonce is available
 * when Helmet builds the Content-Security-Policy header.
 */
export function cspNonceMiddleware(_req: Request, res: Response, next: NextFunction): void {
  res.locals.cspNonce = crypto.randomBytes(16).toString('base64');
  next();
}

/**
 * Returns a Helmet-compatible CSP directive function that resolves to
 * `'nonce-<value>'` using the nonce generated by `cspNonceMiddleware`.
 *
 * Helmet calls this function per-request with the raw Node.js
 * IncomingMessage/ServerResponse. Since Express extends ServerResponse
 * with `locals`, we access the nonce via a type-safe cast.
 *
 * Falls back to returning an empty string if no nonce is available
 * (which effectively becomes a no-op in the CSP header).
 */
export function cspNonceDirective(): (_req: IncomingMessage, res: ServerResponse) => string {
  return (_req: IncomingMessage, res: ServerResponse): string => {
    // Express augments ServerResponse with `locals`; safely access it
    const locals = (res as ServerResponse & { locals?: { cspNonce?: string } }).locals;
    return locals?.cspNonce ? `'nonce-${locals.cspNonce}'` : '';
  };
}
